### ISSUE TITLE
Line 68: helper.py - Python3.4 quote_from_bytes() expected bytes

### ISSUE THREAD

**Issue by PhilippeTrounev** [algolia/algoliasearch-django#14]
Got unicode vs bytes error  running the demo in python 3.4. Fix is below... Stack trace attached..

68 def safe(e):
    """Returns a safe string for URL."""
    return quote(encode(e), safe='')

FIX
68 def safe(e):
    """Returns a safe string for URL."""
    return quote(encode(str(e)), safe='')

 manage.py loaddata contacts.json
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/cypt/Dev/MiMP3/lib/python3.4/site-packages/django/core/management/**init**.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/cypt/Dev/MiMP3/lib/python3.4/site-packages/django/core/management/**init**.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/cypt/Dev/MiMP3/lib/python3.4/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(_args, *_cmd_options)
  File "/home/cypt/Dev/MiMP3/lib/python3.4/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(_args, *_options)
  File "/home/cypt/Dev/MiMP3/lib/python3.4/site-packages/django/core/management/commands/loaddata.py", line 60, in handle
    self.loaddata(fixture_labels)
  File "/home/cypt/Dev/MiMP3/lib/python3.4/site-packages/django/core/management/commands/loaddata.py", line 90, in loaddata
    self.load_label(fixture_label)
  File "/home/cypt/Dev/MiMP3/lib/python3.4/site-packages/django/core/management/commands/loaddata.py", line 147, in load_label
    obj.save(using=self.using)
  File "/home/cypt/Dev/MiMP3/lib/python3.4/site-packages/django/core/serializers/base.py", line 173, in save
    models.Model.save_base(self.object, using=using, raw=True)
  File "/home/cypt/Dev/MiMP3/lib/python3.4/site-packages/django/db/models/base.py", line 747, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/home/cypt/Dev/MiMP3/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/cypt/Dev/MiMP3/lib/python3.4/site-packages/django/contrib/algoliasearch/registration.py", line 126, in __post_save_receiver
    self.update_obj_index(instance)
  File "/home/cypt/Dev/MiMP3/lib/python3.4/site-packages/django/contrib/algoliasearch/registration.py", line 110, in update_obj_index
    adapter.update_obj_index(obj)
  File "/home/cypt/Dev/MiMP3/lib/python3.4/site-packages/django/contrib/algoliasearch/models.py", line 178, in update_obj_index
    self.__index.save_object(obj)
  File "/home/cypt/Dev/MiMP3/lib/python3.4/site-packages/algoliasearch/index.py", line 203, in save_object
    path = '/%s' % safe(obj['objectID'])
  File "/home/cypt/Dev/MiMP3/lib/python3.4/site-packages/algoliasearch/helpers.py", line 68, in safe
    return quote(encode(e), safe='')
  File "/usr/lib/python3.4/urllib/parse.py", line 694, in quote
    return quote_from_bytes(string, safe)
  File "/usr/lib/python3.4/urllib/parse.py", line 719, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: Problem installing fixture '/home/cypt/Dev/MiMP3/MiM/apps/algoliasearch-django-example/contacts.json': quote_from_bytes() expected bytes

**Comment by PLNech** [comment]
Fixed in [algoliasearch-client-python's `fd9593`](https://github.com/algolia/algoliasearch-client-python/commit/fd95937c49207feede05ff912182749ee96c4691).
