### ISSUE TITLE
AttributeError: 'int' object has no attribute 'rstrip' when saving model

### ISSUE THREAD

**Issue by Amrit0991** [algolia/algoliasearch-django#16]
Hi guys,

I have an algolia index set up as below (`index.py`):
```
from django.contrib.algoliasearch import AlgoliaIndex


class ActivityModelIndex(AlgoliaIndex):

    '''Algolia search index for activities'''

    fields = ('activity_type', 'timestamp', 'message', 'additional_data')

    settings = {
        'attributesToIndex': [
            'message', 'additional_data'
        ],

        'numericAttributesToIndex': ['timestamp', 'activity_type']
    }

    index_name = 'activity_index'
```

The model's `pk` is `id`, which is the Django default. Now, Algolia is able to index and apply the settings just fine, but when I try to save a new `ActivityModel`, I get the following error: `AttributeError: 'int' object has no attribute 'rstrip' `

The stack trace takes me all the way down to your `safe` method that is trying to generate a safe URL string from the object's id:
```
Traceback (most recent call last):
  File "/Users/amrit/Code/orms/activity/tests/viewsets/test_activity_viewset.py", line 24, in setUp
    self.contact = create.contact(user=self.user)
  File "/Users/amrit/Code/orms/utils/testing/create.py", line 54, in contact
    contact = contactmodels.ContactModel.objects.create(**contact_kwargs)
  File "/Users/amrit/Code/orms/env/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/amrit/Code/orms/env/lib/python2.7/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/amrit/Code/orms/env/lib/python2.7/site-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/amrit/Code/orms/env/lib/python2.7/site-packages/django/db/models/base.py", line 747, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/Users/amrit/Code/orms/env/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/amrit/Code/orms/activity/signals/ContactReceivers.py", line 29, in log_contact_created
    activity = ActivityModel.objects.create(**activity_kwargs)
  File "/Users/amrit/Code/orms/env/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/amrit/Code/orms/env/lib/python2.7/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/amrit/Code/orms/env/lib/python2.7/site-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/amrit/Code/orms/env/lib/python2.7/site-packages/django/db/models/base.py", line 747, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/Users/amrit/Code/orms/env/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/amrit/Code/orms/env/lib/python2.7/site-packages/django/contrib/algoliasearch/registration.py", line 126, in __post_save_receiver
    self.update_obj_index(instance)
  File "/Users/amrit/Code/orms/env/lib/python2.7/site-packages/django/contrib/algoliasearch/registration.py", line 110, in update_obj_index
    adapter.update_obj_index(obj)
  File "/Users/amrit/Code/orms/env/lib/python2.7/site-packages/django/contrib/algoliasearch/models.py", line 178, in update_obj_index
    self.__index.save_object(obj)
  File "/Users/amrit/Code/orms/env/lib/python2.7/site-packages/algoliasearch/index.py", line 203, in save_object
    path = '/%s' % safe(obj['objectID'])
  File "/Users/amrit/Code/orms/env/lib/python2.7/site-packages/algoliasearch/helpers.py", line 68, in safe
    return quote(encode(e), safe='')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 1283, in quote
    if not s.rstrip(safe):
AttributeError: 'int' object has no attribute 'rstrip'
```

Simply changing `return quote(encode(e), safe='')` to `return quote(encode(str(e)), safe='')` does the trick, but I figured I would ask you guys whether or not I'm doing something wrong before going in an implementing the fix.

I should note that I am also using `Django Rest Framework 3.1.3`, `Django 1.8.2` and `Python 2.7.6`

Thanks,
Amrit

**Comment by dethi** [comment]
Hello @Amrit0991,
Could you please upgrade the package `algoliasearch`. We have fixed this issue in the version 1.6.6 :)

**Comment by Amrit0991** [comment]
haha thank you!

**Comment by dethi** [comment]
You're welcome :smile:
