### ISSUE TITLE
Install fails on pipenv 10.1.0

### ISSUE THREAD

**Issue by dbinetti** [algolia/algoliasearch-django#244]
```
Davids-MacBook:barberscore-api dbinetti$ pipenv install algoliasearch-django
Installing algoliasearch-django…
⠋
Error:  An error occurred while installing algoliasearch-django!
Failed to import the site module
Traceback (most recent call last):
  File "/Users/dbinetti/repos/barberscore-api/.venv/bin/../lib/python3.6/site.py", line 703, in <module>
    main()
  File "/Users/dbinetti/repos/barberscore-api/.venv/bin/../lib/python3.6/site.py", line 683, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "/Users/dbinetti/repos/barberscore-api/.venv/bin/../lib/python3.6/site.py", line 282, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/dbinetti/repos/barberscore-api/.venv/bin/../lib/python3.6/site.py", line 204, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/dbinetti/repos/barberscore-api/.venv/bin/../lib/python3.6/site.py", line 173, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/types.py", line 6, in <module>
    import functools as _functools
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/functools.py", line 24, in <module>
    from types import MappingProxyType
ImportError: cannot import name 'MappingProxyType'

```

**Comment by dbinetti** [comment]
Conflict with other library. Not algolia
