### ISSUE TITLE
latest version of algoliasearch (2.0.0b3) is incompatible with 1.7.0

### ISSUE THREAD

**Issue by ramusus** [algolia/algoliasearch-django#280]
```
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/algoliasearch_django/__init__.py", line 8, in <module>
    from . import models
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/algoliasearch_django/models.py", line 9, in <module>
    from algoliasearch.helpers import AlgoliaException
ImportError: cannot import name 'AlgoliaException'
```

Link to CI: 
https://travis-ci.org/cinemanio/backend/builds/514989723?utm_source=github_status&utm_medium=notification

**Comment by nunomaduro** [comment]
This issue has been fixed on the `algoliasearch-django-1.7.1`. Can you please try again?
